In [1]:
import numpy as np

In [2]:
# 모델의 예측값이라 가정
prediction = np.random.randint(5, size=(10, 20))
prediction

array([[0, 2, 3, 2, 3, 0, 2, 1, 3, 4, 2, 3, 3, 2, 2, 1, 0, 3, 3, 0],
       [0, 2, 4, 0, 2, 2, 2, 2, 1, 3, 0, 1, 1, 4, 4, 0, 0, 4, 3, 3],
       [3, 4, 2, 4, 1, 4, 4, 2, 3, 1, 3, 0, 3, 3, 2, 1, 0, 4, 4, 2],
       [2, 0, 3, 3, 4, 4, 2, 2, 0, 4, 2, 2, 2, 3, 0, 4, 0, 4, 0, 2],
       [2, 3, 0, 2, 0, 2, 1, 0, 1, 0, 2, 2, 0, 4, 4, 0, 0, 3, 2, 1],
       [1, 1, 2, 1, 4, 3, 2, 1, 0, 0, 3, 2, 3, 3, 2, 4, 4, 3, 0, 2],
       [1, 2, 0, 4, 3, 3, 2, 2, 4, 3, 1, 3, 2, 3, 2, 3, 3, 0, 2, 0],
       [4, 2, 3, 4, 2, 4, 1, 4, 4, 4, 1, 0, 3, 4, 2, 3, 0, 4, 4, 2],
       [4, 1, 0, 3, 4, 2, 0, 3, 2, 4, 1, 0, 0, 0, 2, 4, 3, 4, 3, 2],
       [2, 3, 4, 2, 2, 2, 0, 1, 1, 1, 2, 0, 3, 1, 0, 2, 2, 3, 3, 3]])

In [3]:
# 라벨이라 가정
label = np.random.randint(5, size=(10, 20))
label

array([[1, 1, 3, 1, 0, 4, 0, 2, 0, 4, 4, 0, 1, 0, 3, 1, 4, 1, 4, 0],
       [2, 0, 3, 2, 4, 0, 2, 1, 2, 3, 2, 1, 0, 2, 1, 0, 4, 4, 4, 0],
       [0, 4, 3, 1, 0, 4, 4, 0, 1, 2, 1, 0, 4, 1, 1, 3, 1, 4, 3, 4],
       [0, 1, 3, 1, 3, 2, 2, 4, 1, 4, 2, 2, 4, 0, 0, 0, 0, 1, 1, 0],
       [4, 1, 0, 3, 0, 3, 3, 4, 0, 1, 0, 4, 1, 4, 4, 1, 0, 4, 0, 0],
       [4, 0, 3, 4, 2, 1, 4, 3, 4, 4, 1, 3, 4, 4, 4, 0, 3, 3, 0, 0],
       [2, 1, 2, 0, 2, 3, 3, 2, 0, 0, 1, 3, 4, 0, 3, 2, 4, 1, 2, 2],
       [0, 1, 3, 2, 3, 4, 3, 3, 4, 2, 0, 0, 0, 3, 4, 0, 1, 3, 3, 2],
       [4, 1, 2, 3, 0, 2, 1, 2, 3, 3, 1, 4, 4, 4, 3, 3, 1, 1, 4, 3],
       [4, 3, 1, 2, 3, 0, 4, 0, 1, 2, 3, 3, 2, 3, 4, 1, 0, 4, 1, 0]])

In [4]:
n_observed = np.count_nonzero(label)
diff = prediction - label
diff

array([[-1,  1,  0,  1,  3, -4,  2, -1,  3,  0, -2,  3,  2,  2, -1,  0,
        -4,  2, -1,  0],
       [-2,  2,  1, -2, -2,  2,  0,  1, -1,  0, -2,  0,  1,  2,  3,  0,
        -4,  0, -1,  3],
       [ 3,  0, -1,  3,  1,  0,  0,  2,  2, -1,  2,  0, -1,  2,  1, -2,
        -1,  0,  1, -2],
       [ 2, -1,  0,  2,  1,  2,  0, -2, -1,  0,  0,  0, -2,  3,  0,  4,
         0,  3, -1,  2],
       [-2,  2,  0, -1,  0, -1, -2, -4,  1, -1,  2, -2, -1,  0,  0, -1,
         0, -1,  2,  1],
       [-3,  1, -1, -3,  2,  2, -2, -2, -4, -4,  2, -1, -1, -1, -2,  4,
         1,  0,  0,  2],
       [-1,  1, -2,  4,  1,  0, -1,  0,  4,  3,  0,  0, -2,  3, -1,  1,
        -1, -1,  0, -2],
       [ 4,  1,  0,  2, -1,  0, -2,  1,  0,  2,  1,  0,  3,  1, -2,  3,
        -1,  1,  1,  0],
       [ 0,  0, -2,  0,  4,  0, -1,  1, -1,  1,  0, -4, -4, -4, -1,  1,
         2,  3, -1, -1],
       [-2,  0,  3,  0, -1,  2, -4,  1,  0, -1, -1, -3,  1, -2, -4,  1,
         2, -1,  2,  3]])

In [5]:
print(n_observed)

154


In [6]:
square_diff = np.einsum('BH, BH->B', diff, diff)
square_diff

array([ 85,  67,  49,  62,  48, 100,  70,  58,  89,  86])

In [7]:
loss = np.sqrt(np.sum(square_diff)/ n_observed)
loss

2.15322168769582

In [14]:
def masked_rmse(prediction, y):
    mask = y.nonzero()
    diff = prediction - y
    n_observed = np.count_nonzero(label)
    square_diff = np.einsum('BH,BH->B', diff, diff)
    loss = np.sqrt(np.sum(square_diff)/ n_observed)
    return loss

In [15]:
loss_result = masked_rmse(prediction, label)
loss_result

2.15322168769582